In [ ]:
class MeraLR:

        def _init_(self): #constructor
               self.m = None
               self.b = None

        def fit(self,x_train,y_train):

                num = 0
                den = 0
                
                for i in range(x_train.shape[0]):
                        num = num + ((x_train[i] - x_train.mean())*(y_train[i] - y_train.mean()))
                        den = den + ((x_train[i] - x_train.mean())*(x_train[i] - x_train.mean()))

                        self.m = num/den
                        self.b = y_train.mean() - (self.m * x_train.mean())
                        print(self.m)
                        print(self.b)


        def predict(self,x_test):

            print(x_test)

                return self.m * x_test + self.b

In [1]:
import numpy as np
import pandas as pd

In [27]:
df = pd.read_csv('datasc2.csv')

In [28]:
df.head()

x      y
0   28  79.99
1   28  61.89
2  270  40.27
3  365  41.05
4  360  44.50

In [13]:
x = df.iloc[:,0].values
y = df.iloc[:,1].values

In [14]:
x

array([ 28,  28, 270, 365, 360,  90, 365,  28,  28,  28,  90,  28, 270,
        90,  28,  90,  90, 365,  90, 180, 180,  28,   3, 180, 365, 270,
       270, 180,  28])

In [15]:
y

array([79.99, 61.89, 40.27, 41.05, 44.5 , 47.03, 43.7 , 36.45, 45.85,
       39.29, 38.07, 28.02, 43.01, 42.33, 47.81, 52.91, 39.36, 56.14,
       40.56, 42.62, 41.84, 28.24,  8.06, 44.21, 52.52, 53.3 , 41.15,
       52.12, 37.43])

In [29]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=2)

In [17]:
x_train.shape

(23,)

In [34]:
lr = MeraLR()

In [43]:
lr.fit(x_train,y_train)

0.024348341232227455
37.16864928909953
0.01403062931866812
38.85447369654109
0.007225738395244172
39.96633370046401
0.007484174480528917
39.92410749139879
0.009549784991698953
39.58660469570414
0.008452242318840454
39.76593362459989
0.009384877132347638
39.613549205940764
0.011379719092192616
39.28760937615392
0.012448063923077927
39.113051120742305
0.009318521485293932
39.62439114166371
0.018190229497451152
38.174831197764284
0.028646863629074173
36.4663081079104
0.026822664590397224
36.76436636822988
0.027404157414874467
36.66935549716964
0.031197750788255686
36.04951532772761
0.031360503322966846
36.02292297879524
0.030885798603653983
36.10048560206384
0.035159013281360514
35.40227948211509
0.04939950622077344
33.075506766188404
0.048171052812349666
33.276225370921296
0.047130718834950125
33.44620689644597
0.043827928287656824
33.98585415195589
0.03978913049203739
34.64575859177928


In [20]:
x_train.shape[0]

23

In [21]:
x_train[0]

np.int64(90)

In [22]:
x_train

array([ 90, 365, 365, 180, 180, 270, 270, 360,  90,  90,  28, 365, 270,
        28, 270, 180,  90,  28,   3,  28,  90,  90,  28])

In [36]:
x_test[0]

np.int64(28)

In [45]:
print(lr.predict(x_test[0]))

None
