<a href="https://colab.research.google.com/github/MLEbyNoman/MLStudio/blob/main/PYTORCH_BASIC_EPISODE_NO_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Introduction to tensor**

In [2]:
import torch
torch.__version__

'2.9.0+cpu'

# **creating tensors**

# 1. **Scalar**

In [3]:
scalar=torch.tensor(8)
scalar

tensor(8)

In [4]:
scalar.ndim

0

In [5]:
scalar.shape

torch.Size([])

In [6]:
scalar.item()

8

# **2.vector**

In [7]:
vector=torch.tensor([1,2,3])
vector

tensor([1, 2, 3])

In [8]:
vector.ndim


1

In [9]:
vector.shape

torch.Size([3])

# **3.Matrix**

In [10]:
matrix=torch.tensor([[1,2,3],[4,5,6]])
matrix

tensor([[1, 2, 3],
        [4, 5, 6]])

In [11]:
matrix.ndim

2

In [12]:
matrix.shape

torch.Size([2, 3])

In [13]:
tensor=torch.tensor([[[[[1,2,3,4,5],
                      [5,6,7,8,3],
                      [9,5,4,2,8]]]]])
tensor

tensor([[[[[1, 2, 3, 4, 5],
           [5, 6, 7, 8, 3],
           [9, 5, 4, 2, 8]]]]])

In [14]:
tensor.ndim

5

In [15]:
tensor.shape

torch.Size([1, 1, 1, 3, 5])

# ***3.Random_Tensor***

In [16]:
random_tensor=torch.rand(3,4)
random_tensor

tensor([[0.6573, 0.2742, 0.2920, 0.5425],
        [0.2118, 0.7784, 0.3603, 0.4114],
        [0.5625, 0.1645, 0.4036, 0.2722]])

In [17]:
bigger_tensor=torch.rand(1,1,3,4)
bigger_tensor

tensor([[[[0.4393, 0.0259, 0.9501, 0.3445],
          [0.3237, 0.8677, 0.4804, 0.4334],
          [0.1183, 0.7823, 0.3751, 0.4964]]]])

In [18]:
bigger_tensor=torch.rand(5,2,3)
bigger_tensor

tensor([[[0.4355, 0.7382, 0.8644],
         [0.8629, 0.8868, 0.2673]],

        [[0.5360, 0.6574, 0.2360],
         [0.3453, 0.0207, 0.3291]],

        [[0.8806, 0.0545, 0.8577],
         [0.9363, 0.0309, 0.6267]],

        [[0.1579, 0.8150, 0.2057],
         [0.5389, 0.7070, 0.5267]],

        [[0.3388, 0.9017, 0.9688],
         [0.4753, 0.6119, 0.0920]]])

In [19]:
zeros=torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [20]:
zeros=torch.zeros(3,3,4)
zeros

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [21]:
ones=torch.ones(2,6)
ones

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])

In [22]:
ones=torch.ones(3,2,6)
ones

tensor([[[1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.]]])

# **Creating arange and tensor_like**

In [23]:
x =torch.arange(start=0,end=20)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19])

In [24]:
x =torch.arange(0,20)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19])

In [25]:
x =torch.arange(start=0,end=20,step=2)
x

tensor([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [26]:
x =torch.arange(0,100,2)
x

tensor([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
        36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70,
        72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [27]:
sample = torch.rand(3,4)
sample

tensor([[0.1182, 0.9453, 0.7057, 0.5116],
        [0.9424, 0.5210, 0.2056, 0.0220],
        [0.8248, 0.5201, 0.8682, 0.5836]])

In [28]:
zeros_like_tensor = torch.zeros_like(sample)
zeros_like_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [29]:
ones_like_tensor = torch.ones_like(sample)
ones_like_tensor

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

# **Torch Eye(use in Masking concepts)**

In [30]:
torch_eye = torch.eye(2)
torch_eye

tensor([[1., 0.],
        [0., 1.]])

In [31]:
torch_eye = torch.eye(4,2)
torch_eye

tensor([[1., 0.],
        [0., 1.],
        [0., 0.],
        [0., 0.]])

**Torch.full(Tensor values can be defined as required.)**

In [32]:
full_tensor = torch.full((5,3),7)
full_tensor

tensor([[7, 7, 7],
        [7, 7, 7],
        [7, 7, 7],
        [7, 7, 7],
        [7, 7, 7]])

In [33]:
full_tensor = torch.full((4,3),9)
full_tensor

tensor([[9, 9, 9],
        [9, 9, 9],
        [9, 9, 9],
        [9, 9, 9]])

**Torch.linspace(torch.linspace divides an interval into equal parts and returns the points.)**

In [34]:
linear_tensor = torch.linspace(1,10,5)
linear_tensor

tensor([ 1.0000,  3.2500,  5.5000,  7.7500, 10.0000])

In [35]:
linear_tensor = torch.linspace(1,10,50)
linear_tensor

tensor([ 1.0000,  1.1837,  1.3673,  1.5510,  1.7347,  1.9184,  2.1020,  2.2857,
         2.4694,  2.6531,  2.8367,  3.0204,  3.2041,  3.3878,  3.5714,  3.7551,
         3.9388,  4.1224,  4.3061,  4.4898,  4.6735,  4.8571,  5.0408,  5.2245,
         5.4082,  5.5918,  5.7755,  5.9592,  6.1429,  6.3265,  6.5102,  6.6939,
         6.8776,  7.0612,  7.2449,  7.4286,  7.6122,  7.7959,  7.9796,  8.1633,
         8.3469,  8.5306,  8.7143,  8.8980,  9.0816,  9.2653,  9.4490,  9.6327,
         9.8163, 10.0000])

# **Tensor DataTypes** (Think of bits like digits in a number:

16-bit → short number (less detail)

32-bit → normal number (good detail)

64-bit → very long number (very high detail)

More bits = more accuracy and bigger rang)

In [36]:
sample = torch.rand(3,4)
sample

tensor([[0.2884, 0.0791, 0.3765, 0.8410],
        [0.5579, 0.1042, 0.6892, 0.7130],
        [0.8594, 0.3984, 0.4508, 0.9581]])

In [37]:
sample.dtype

torch.float32

In [38]:
sample=torch.arange(3.,4.,dtype=int)
sample,sample.dtype

(tensor([3]), torch.int64)

# ***Change Tensor DataType***

In [40]:
x = torch.arange(1.,10.)
x,x.dtype

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.float32)

In [41]:
tensor_float16=x.type(torch.float16)
tensor_float16

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=torch.float16)

In [42]:
tensor_int8=x.type(torch.int8)
tensor_int8

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=torch.int8)

**Getting Information from Tensor(shape,dtype,device)**

In [43]:
some_tensor=torch.rand(3,4)
some_tensor

tensor([[0.1921, 0.8210, 0.6518, 0.5243],
        [0.6455, 0.8268, 0.7114, 0.5260],
        [0.7208, 0.0503, 0.3781, 0.0214]])

In [44]:
some_tensor.shape

torch.Size([3, 4])

In [45]:
some_tensor.device

device(type='cpu')