<a href="https://colab.research.google.com/github/MLEbyNoman/MLStudio/blob/main/PYTORCH_BASIC_EPISODE_NO_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Introduction to tensor**

In [2]:
import torch
torch.__version__

'2.9.0+cpu'

# **creating tensors**

# 1. **Scalar**

In [3]:
scalar=torch.tensor(8)
scalar

tensor(8)

In [4]:
scalar.ndim

0

In [5]:
scalar.shape

torch.Size([])

In [6]:
scalar.item()

8

# **2.vector**

In [9]:
vector=torch.tensor([1,2,3])
vector

tensor([1, 2, 3])

In [10]:
vector.ndim


1

In [11]:
vector.shape

torch.Size([3])

# **3.Matrix**

In [13]:
matrix=torch.tensor([[1,2,3],[4,5,6]])
matrix

tensor([[1, 2, 3],
        [4, 5, 6]])

In [14]:
matrix.ndim

2

In [15]:
matrix.shape

torch.Size([2, 3])

In [23]:
tensor=torch.tensor([[[[[1,2,3,4,5],
                      [5,6,7,8,3],
                      [9,5,4,2,8]]]]])
tensor

tensor([[[[[1, 2, 3, 4, 5],
           [5, 6, 7, 8, 3],
           [9, 5, 4, 2, 8]]]]])

In [24]:
tensor.ndim

5

In [25]:
tensor.shape

torch.Size([1, 1, 1, 3, 5])

# ***3.Random_Tensor***

In [27]:
random_tensor=torch.rand(3,4)
random_tensor

tensor([[0.4078, 0.0268, 0.3076, 0.3343],
        [0.8376, 0.5978, 0.2209, 0.2130],
        [0.3694, 0.4570, 0.5337, 0.6723]])

In [28]:
bigger_tensor=torch.rand(1,1,3,4)
bigger_tensor

tensor([[[[0.8476, 0.1426, 0.4900, 0.5029],
          [0.8236, 0.2711, 0.3119, 0.7468],
          [0.4374, 0.2486, 0.8283, 0.2564]]]])

In [31]:
bigger_tensor=torch.rand(5,2,3)
bigger_tensor

tensor([[[0.9657, 0.4016, 0.9376],
         [0.2675, 0.3122, 0.8324]],

        [[0.0071, 0.0537, 0.7144],
         [0.9506, 0.9207, 0.0701]],

        [[0.7929, 0.1131, 0.4091],
         [0.1643, 0.4599, 0.1946]],

        [[0.6225, 0.1446, 0.1077],
         [0.3320, 0.2900, 0.7873]],

        [[0.8332, 0.7388, 0.5677],
         [0.7254, 0.5185, 0.5585]]])

In [38]:
zeros=torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [35]:
zeros=torch.zeros(3,3,4)
zeros

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [33]:
ones=torch.ones(2,6)
ones

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])

In [36]:
ones=torch.ones(3,2,6)
ones

tensor([[[1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.]]])

# **Creating arange and tensor_like**

In [41]:
x =torch.arange(start=0,end=20)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19])

In [40]:
x =torch.arange(0,20)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19])

In [42]:
x =torch.arange(start=0,end=20,step=2)
x

tensor([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [44]:
x =torch.arange(0,100,2)
x

tensor([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
        36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70,
        72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [45]:
sample = torch.rand(3,4)
sample

tensor([[0.5458, 0.1971, 0.2601, 0.0871],
        [0.4632, 0.6104, 0.4662, 0.5045],
        [0.0030, 0.6920, 0.7947, 0.8117]])

In [46]:
zeros_like_tensor = torch.zeros_like(sample)
zeros_like_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [48]:
ones_like_tensor = torch.ones_like(sample)
ones_like_tensor

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

# **Torch Eye(use in Masking concepts)**

In [49]:
torch_eye = torch.eye(2)
torch_eye

tensor([[1., 0.],
        [0., 1.]])

In [53]:
torch_eye = torch.eye(4,2)
torch_eye

tensor([[1., 0.],
        [0., 1.],
        [0., 0.],
        [0., 0.]])

**Torch.full(Tensor values can be defined as required.)**

In [54]:
full_tensor = torch.full((5,3),7)
full_tensor

tensor([[7, 7, 7],
        [7, 7, 7],
        [7, 7, 7],
        [7, 7, 7],
        [7, 7, 7]])

In [56]:
full_tensor = torch.full((4,3),9)
full_tensor

tensor([[9, 9, 9],
        [9, 9, 9],
        [9, 9, 9],
        [9, 9, 9]])

**Torch.linspace(torch.linspace divides an interval into equal parts and returns the points.)**

In [57]:
linear_tensor = torch.linspace(1,10,5)
linear_tensor

tensor([ 1.0000,  3.2500,  5.5000,  7.7500, 10.0000])

In [58]:
linear_tensor = torch.linspace(1,10,50)
linear_tensor

tensor([ 1.0000,  1.1837,  1.3673,  1.5510,  1.7347,  1.9184,  2.1020,  2.2857,
         2.4694,  2.6531,  2.8367,  3.0204,  3.2041,  3.3878,  3.5714,  3.7551,
         3.9388,  4.1224,  4.3061,  4.4898,  4.6735,  4.8571,  5.0408,  5.2245,
         5.4082,  5.5918,  5.7755,  5.9592,  6.1429,  6.3265,  6.5102,  6.6939,
         6.8776,  7.0612,  7.2449,  7.4286,  7.6122,  7.7959,  7.9796,  8.1633,
         8.3469,  8.5306,  8.7143,  8.8980,  9.0816,  9.2653,  9.4490,  9.6327,
         9.8163, 10.0000])