<a href="https://colab.research.google.com/github/MLEbyNoman/MLStudio/blob/main/PYTORCH_BASIC_EPISODE_NO_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Introduction to tensor**

In [2]:
import torch
torch.__version__

'2.9.0+cpu'

# **creating tensors**

# 1. **Scalar**

In [3]:
scalar=torch.tensor(8)
scalar

tensor(8)

In [4]:
scalar.ndim

0

In [5]:
scalar.shape

torch.Size([])

In [6]:
scalar.item()

8

# **2.vector**

In [9]:
vector=torch.tensor([1,2,3])
vector

tensor([1, 2, 3])

In [10]:
vector.ndim


1

In [11]:
vector.shape

torch.Size([3])

# **3.Matrix**

In [13]:
matrix=torch.tensor([[1,2,3],[4,5,6]])
matrix

tensor([[1, 2, 3],
        [4, 5, 6]])

In [14]:
matrix.ndim

2

In [15]:
matrix.shape

torch.Size([2, 3])

In [23]:
tensor=torch.tensor([[[[[1,2,3,4,5],
                      [5,6,7,8,3],
                      [9,5,4,2,8]]]]])
tensor

tensor([[[[[1, 2, 3, 4, 5],
           [5, 6, 7, 8, 3],
           [9, 5, 4, 2, 8]]]]])

In [24]:
tensor.ndim

5

In [25]:
tensor.shape

torch.Size([1, 1, 1, 3, 5])

# ***3.Random_Tensor***

In [27]:
random_tensor=torch.rand(3,4)
random_tensor

tensor([[0.4078, 0.0268, 0.3076, 0.3343],
        [0.8376, 0.5978, 0.2209, 0.2130],
        [0.3694, 0.4570, 0.5337, 0.6723]])

In [28]:
bigger_tensor=torch.rand(1,1,3,4)
bigger_tensor

tensor([[[[0.8476, 0.1426, 0.4900, 0.5029],
          [0.8236, 0.2711, 0.3119, 0.7468],
          [0.4374, 0.2486, 0.8283, 0.2564]]]])

In [31]:
bigger_tensor=torch.rand(5,2,3)
bigger_tensor

tensor([[[0.9657, 0.4016, 0.9376],
         [0.2675, 0.3122, 0.8324]],

        [[0.0071, 0.0537, 0.7144],
         [0.9506, 0.9207, 0.0701]],

        [[0.7929, 0.1131, 0.4091],
         [0.1643, 0.4599, 0.1946]],

        [[0.6225, 0.1446, 0.1077],
         [0.3320, 0.2900, 0.7873]],

        [[0.8332, 0.7388, 0.5677],
         [0.7254, 0.5185, 0.5585]]])

In [38]:
zeros=torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [35]:
zeros=torch.zeros(3,3,4)
zeros

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [33]:
ones=torch.ones(2,6)
ones

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])

In [36]:
ones=torch.ones(3,2,6)
ones

tensor([[[1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.]]])