<a href="https://colab.research.google.com/github/MLEbyNoman/MLStudio/blob/main/PYTORCH_BASIC_EPISODE_NO_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Introduction to tensor**

In [1]:
import torch
torch.__version__

'2.9.0+cpu'

# **creating tensors**

# 1. **Scalar**

In [2]:
scalar=torch.tensor(8)
scalar

tensor(8)

In [3]:
scalar.ndim

0

In [4]:
scalar.shape

torch.Size([])

In [5]:
scalar.item()

8

# **2.vector**

In [6]:
vector=torch.tensor([1,2,3])
vector

tensor([1, 2, 3])

In [7]:
vector.ndim


1

In [8]:
vector.shape

torch.Size([3])

# **3.Matrix**

In [9]:
matrix=torch.tensor([[1,2,3],[4,5,6]])
matrix

tensor([[1, 2, 3],
        [4, 5, 6]])

In [10]:
matrix.ndim

2

In [11]:
matrix.shape

torch.Size([2, 3])

In [12]:
tensor=torch.tensor([[[[[1,2,3,4,5],
                      [5,6,7,8,3],
                      [9,5,4,2,8]]]]])
tensor

tensor([[[[[1, 2, 3, 4, 5],
           [5, 6, 7, 8, 3],
           [9, 5, 4, 2, 8]]]]])

In [13]:
tensor.ndim

5

In [14]:
tensor.shape

torch.Size([1, 1, 1, 3, 5])

# ***3.Random_Tensor***

In [15]:
random_tensor=torch.rand(3,4)
random_tensor

tensor([[0.7749, 0.2202, 0.4985, 0.7252],
        [0.1571, 0.6980, 0.3152, 0.9464],
        [0.5997, 0.2873, 0.2883, 0.1392]])

In [16]:
bigger_tensor=torch.rand(1,1,3,4)
bigger_tensor

tensor([[[[0.2595, 0.2730, 0.2182, 0.7898],
          [0.1267, 0.4202, 0.2678, 0.0898],
          [0.5729, 0.1238, 0.2849, 0.3300]]]])

In [17]:
bigger_tensor=torch.rand(5,2,3)
bigger_tensor

tensor([[[0.3682, 0.0085, 0.4319],
         [0.5403, 0.8731, 0.6047]],

        [[0.0044, 0.8862, 0.3646],
         [0.4591, 0.1166, 0.2595]],

        [[0.5711, 0.5919, 0.0878],
         [0.6692, 0.8714, 0.0474]],

        [[0.3096, 0.2851, 0.6780],
         [0.8940, 0.7498, 0.3486]],

        [[0.6988, 0.6919, 0.6045],
         [0.9090, 0.2688, 0.7919]]])

In [18]:
zeros=torch.zeros(3,4)
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [19]:
zeros=torch.zeros(3,3,4)
zeros

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [20]:
ones=torch.ones(2,6)
ones

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])

In [21]:
ones=torch.ones(3,2,6)
ones

tensor([[[1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.]]])

# **Creating arange and tensor_like**

In [22]:
x =torch.arange(start=0,end=20)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19])

In [23]:
x =torch.arange(0,20)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19])

In [24]:
x =torch.arange(start=0,end=20,step=2)
x

tensor([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [25]:
x =torch.arange(0,100,2)
x

tensor([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34,
        36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66, 68, 70,
        72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [26]:
sample = torch.rand(3,4)
sample

tensor([[0.6208, 0.1770, 0.9964, 0.6210],
        [0.3530, 0.7521, 0.7001, 0.4823],
        [0.1125, 0.4387, 0.8423, 0.1848]])

In [27]:
zeros_like_tensor = torch.zeros_like(sample)
zeros_like_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [28]:
ones_like_tensor = torch.ones_like(sample)
ones_like_tensor

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

# **Torch Eye(use in Masking concepts)**

In [29]:
torch_eye = torch.eye(2)
torch_eye

tensor([[1., 0.],
        [0., 1.]])

In [30]:
torch_eye = torch.eye(4,2)
torch_eye

tensor([[1., 0.],
        [0., 1.],
        [0., 0.],
        [0., 0.]])

**Torch.full(Tensor values can be defined as required.)**

In [31]:
full_tensor = torch.full((5,3),7)
full_tensor

tensor([[7, 7, 7],
        [7, 7, 7],
        [7, 7, 7],
        [7, 7, 7],
        [7, 7, 7]])

In [32]:
full_tensor = torch.full((4,3),9)
full_tensor

tensor([[9, 9, 9],
        [9, 9, 9],
        [9, 9, 9],
        [9, 9, 9]])

**Torch.linspace(torch.linspace divides an interval into equal parts and returns the points.)**

In [33]:
linear_tensor = torch.linspace(1,10,5)
linear_tensor

tensor([ 1.0000,  3.2500,  5.5000,  7.7500, 10.0000])

In [34]:
linear_tensor = torch.linspace(1,10,50)
linear_tensor

tensor([ 1.0000,  1.1837,  1.3673,  1.5510,  1.7347,  1.9184,  2.1020,  2.2857,
         2.4694,  2.6531,  2.8367,  3.0204,  3.2041,  3.3878,  3.5714,  3.7551,
         3.9388,  4.1224,  4.3061,  4.4898,  4.6735,  4.8571,  5.0408,  5.2245,
         5.4082,  5.5918,  5.7755,  5.9592,  6.1429,  6.3265,  6.5102,  6.6939,
         6.8776,  7.0612,  7.2449,  7.4286,  7.6122,  7.7959,  7.9796,  8.1633,
         8.3469,  8.5306,  8.7143,  8.8980,  9.0816,  9.2653,  9.4490,  9.6327,
         9.8163, 10.0000])

# **Tensor DataTypes** (Think of bits like digits in a number:

16-bit → short number (less detail)

32-bit → normal number (good detail)

64-bit → very long number (very high detail)

More bits = more accuracy and bigger rang)

In [35]:
sample = torch.rand(3,4)
sample

tensor([[0.0619, 0.4816, 0.0464, 0.5893],
        [0.3045, 0.7057, 0.4341, 0.6581],
        [0.3967, 0.7873, 0.9472, 0.0030]])

In [36]:
sample.dtype

torch.float32

In [37]:
sample=torch.arange(3.,4.,dtype=int)
sample,sample.dtype

(tensor([3]), torch.int64)

# ***Change Tensor DataType***

In [38]:
x = torch.arange(1.,10.)
x,x.dtype

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.float32)

In [39]:
tensor_float16=x.type(torch.float16)
tensor_float16

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.], dtype=torch.float16)

In [40]:
tensor_int8=x.type(torch.int8)
tensor_int8

tensor([1, 2, 3, 4, 5, 6, 7, 8, 9], dtype=torch.int8)

**Getting Information from Tensor(shape,dtype,device)**

In [41]:
some_tensor=torch.rand(3,4)
some_tensor

tensor([[0.7959, 0.8404, 0.7368, 0.7851],
        [0.9818, 0.0487, 0.1229, 0.0899],
        [0.1439, 0.4924, 0.3218, 0.3058]])

In [42]:
some_tensor.shape

torch.Size([3, 4])

In [43]:
some_tensor.device

device(type='cpu')

# **Manipulating Tensor** (Tensor operations)
1. Addition
2. Subtraction
3. Multiplication
4. Divivsion
5. Matrix multiplication

**1.Addition**

In [44]:
tensor = torch.tensor([1,2,3])

In [45]:
tensor + 10

tensor([11, 12, 13])

In [46]:
tensor_a = torch.tensor([1,2,3,4])
tensor_b = torch.tensor([5,6,7,8])
tensor_a,tensor_b

(tensor([1, 2, 3, 4]), tensor([5, 6, 7, 8]))

In [47]:
tensor_a + tensor_b

tensor([ 6,  8, 10, 12])

In [48]:
torch.add(tensor_a,tensor_b)

tensor([ 6,  8, 10, 12])

**2.Subtraction**

In [49]:
tensor = torch.tensor([1,2,3])
tensor

tensor([1, 2, 3])

In [52]:
tensor - 10

tensor([-9, -8, -7])

In [54]:
torch.subtract(tensor,10)

tensor([-9, -8, -7])

In [55]:
tensor_a = torch.tensor([1,2,3])
tensor_b = torch.tensor([4,5,6])
tensor_a,tensor_b

(tensor([1, 2, 3]), tensor([4, 5, 6]))

In [56]:
torch.sub(tensor_a,tensor_b)

tensor([-3, -3, -3])

**3.Multiplication(element-wise)**

In [57]:
tensor=torch.tensor([1,2,3])
tensor

tensor([1, 2, 3])

In [58]:
tensor * 10

tensor([10, 20, 30])

In [59]:
torch.multiply(tensor,5)

tensor([ 5, 10, 15])

In [60]:
torch.mul(tensor,10)

tensor([10, 20, 30])

In [61]:
tensor

tensor([1, 2, 3])

In [62]:
tensor * tensor

tensor([1, 4, 9])

**4. Division**

In [63]:
tensor = torch.tensor([1,2,3])
tensor

tensor([1, 2, 3])

In [64]:
tensor / 10

tensor([0.1000, 0.2000, 0.3000])

**5. Matrix multiplication**

In [65]:
matrix_a=torch.tensor([[1,2],
                        [3,4]])
matrix_b=torch=torch.tensor([[5,6],
                              [7,8]])
matrix_a,matrix_b

(tensor([[1, 2],
         [3, 4]]),
 tensor([[5, 6],
         [7, 8]]))