<a href="https://colab.research.google.com/github/MLEbyNoman/MLStudio/blob/main/PYTORCH_BASIC_EPISODE_NO_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Introduction to tensor**

In [2]:
import torch
torch.__version__

'2.9.0+cpu'

# **creating tensors**

# 1. **Scalar**

In [3]:
scalar=torch.tensor(8)
scalar

tensor(8)

In [4]:
scalar.ndim

0

In [5]:
scalar.shape

torch.Size([])

In [6]:
scalar.item()

8

# **2.vector**

In [9]:
vector=torch.tensor([1,2,3])
vector

tensor([1, 2, 3])

In [10]:
vector.ndim


1

In [11]:
vector.shape

torch.Size([3])

# **3.Matrix**

In [13]:
matrix=torch.tensor([[1,2,3],[4,5,6]])
matrix

tensor([[1, 2, 3],
        [4, 5, 6]])

In [14]:
matrix.ndim

2

In [15]:
matrix.shape

torch.Size([2, 3])

In [23]:
tensor=torch.tensor([[[[[1,2,3,4,5],
                      [5,6,7,8,3],
                      [9,5,4,2,8]]]]])
tensor

tensor([[[[[1, 2, 3, 4, 5],
           [5, 6, 7, 8, 3],
           [9, 5, 4, 2, 8]]]]])

In [24]:
tensor.ndim

5

In [25]:
tensor.shape

torch.Size([1, 1, 1, 3, 5])